apiVersion: apps/v1
kind: Deployment
metadata:
  name: kafka
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      app: kafka
  template:
    metadata:
      labels:
        app: kafka
    spec:
      containers:
      - name: kafka
        image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
        env:
        - name: KAFKA_ZOOKEEPER_CONNECT
          value: "{{ .Values.env.KAFKA_ZOOKEEPER_CONNECT }}"
        - name: KAFKA_ADVERTISED_LISTENERS
          value: "{{ .Values.env.KAFKA_ADVERTISED_LISTENERS }}"
---
apiVersion: v1
kind: Service
metadata:
  name: kafka
spec:
  type: ClusterIP
  selector:
    app: kafka
  ports:
    - protocol: TCP
      port: {{ .Values.service.port }}
      targetPort: 9092