apiVersion: apps/v1
kind: Deployment
metadata:
  name: sidekiq
  labels:
    app: sidekiq
spec:
  replicas: 2
  selector:
    matchLabels:
      app: sidekiq
  template:
    metadata:
      labels:
        app: sidekiq
    spec:
      containers:
        - name: sidekiq
          image: myregistry/sidekiq:latest
          env:
            - name: REDIS_URL
              value: "redis://redis:6379/0"
            - name: DATABASE_URL
              value: "postgres://user:password@postgres:5432/mydatabase"
          resources:
            requests:
              cpu: "250m"
              memory: "256Mi"
            limits:
              cpu: "500m"
              memory: "512Mi"