apiVersion: v2
name: rails-microservices
description: A Helm chart for Rails microservices with Kafka and Sidekiq
type: application
version: 1.0.0
appVersion: 1.0.0
dependencies:
  - name: order-service
    version: 1.0.0
    repository: file://charts/order-service
  - name: payment-service
    version: 1.0.0
    repository: file://charts/payment-service
  - name: kafka
    version: 1.0.0
    repository: file://charts/kafka
  - name: zookeeper
    version: 1.0.0
    repository: file://charts/zookeeper
  - name: postgres
    version: 1.0.0
    repository: file://charts/postgres
  - name: redis
    version: 1.0.0
    repository: file://charts/redis
  - name: sidekiq
    version: 1.0.0
    repository: file://charts/sidekiq
