replicaCount: 2
image:
  repository: myregistry/sidekiq
  tag: latest
  pullPolicy: IfNotPresent
env:
  REDIS_URL: redis://redis:6379/0
  DATABASE_URL: postgres://user:password@postgres:5432/mydatabase