name: Deploy Helm Charts

on:
  push:
    branches:
      - master

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3

      - name: Setup Helm
        uses: azure/setup-helm@v3
        with:
          version: latest

      - name: Configure Kubernetes Access
        env:
          KUBE_CONFIG: ${{ secrets.KUBECONFIG }}
        run: |
          echo "$KUBE_CONFIG" | base64 --decode > kubeconfig.yaml
          export KUBECONFIG=$(pwd)/kubeconfig.yaml

      - name: Deploy Helm Chart
        run: |
          helm upgrade --install rails-microservices ./helm-charts